---
apiVersion: v1
kind: Namespace
metadata:
  name: moinmoin
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: moinmoin-pvc
  namespace: moinmoin
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: ext4
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moinmoin
  namespace: moinmoin
  labels:
    app: moinmoin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moinmoin
  template:
    metadata:
      labels:
        app: moinmoin
    spec:
      volumes:
        - name: moinmoin-vol
          persistentVolumeClaim:
            claimName: moinmoin-pvc
      containers:
      - name: moinmoin
        image: alexandreroman/moinmoin-wiki:1.9.10.fixinit
        env:
          - name: NOSSL
            value: "1"
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
          - name: moinmoin-vol
            mountPath: /usr/local/share/moin/data
---
apiVersion: v1
kind: Service
metadata:
  name: moinmoin-lb
  labels:
    app: moinmoin
  namespace: moinmoin
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: moinmoin
